### ISSUE TITLE
Close

### ISSUE THREAD

**Issue by yuanze-lin** [hmorimitsu/maskgit-torch#1]

**Comment by hmorimitsu** [comment]
Hi,

I have just tried to translate the official demo notebook at [https://github.com/google-research/maskgit/blob/main/MaskGIT_demo.ipynb](https://github.com/google-research/maskgit/blob/main/MaskGIT_demo.ipynb) to work with this code, and it seems to produce similar results in image editing.

But I have not done extensive experiments with it.
